### ISSUE TITLE
error of running docker image

### ISSUE THREAD

**Issue by SherlockNovitch** [ASSERT-KTH/jdbl-experiments#17]
I build the dockerfile and run it . There is an AttributeError when running python srcipt.

```
docker run -v `pwd`/results:/results -it --rm jdbl debloat -d https://github.com/apache/commons-cli.git -c https://github.com/1dir1/wordpress-java.git
1. Clone library...
2. Clone client...
3. Extract library version
4. Checkout library version
/tmp/tmp_dcec81e
Traceback (most recent call last):
  File "/home/jdbl/./jdbl.py", line 22, in <module>
    jdbl.run()
  File "/home/jdbl/core/JDBL.py", line 114, in run
    current_status['success'] = self.library.checkout_version(
  File "/home/jdbl/core/Project.py", line 43, in checkout_version
    releases = self.get_releases()
AttributeError: 'Project' object has no attribute 'get_releases'
```

I check the source code and find that there is no definition of the 'get_releases' function. I think there may be some problems in this repository , but I don't know how to debug. Or my usage method is wrong, I hope to get your answer, thank you very much.

**Comment by tdurieux** [comment]
I just pushed 3dc2e5f877894023732459f69561971f61d0883e which fixes your problem.

Unfortunately the tests https://github.com/1dir1/wordpress-java.git of fails in our docker container.

You should run this cmd to have the results
`docker run -v `pwd`/results:/home/jdbl/results/-it --rm jdbl debloat -d https://github.com/apache/commons-cli.git -c https://github.com/1dir1/wordpress-java.git`

**Comment by SherlockNovitch** [comment]
![image](https://github.com/ASSERT-KTH/jdbl-experiments/assets/126306048/1c5151e4-5471-4c08-b3f4-18b074ac7446)
I am confronted with a new error when executing client tests . What should I do? Should I modify the dockerfile?

Another issue is that the dockerfile updated in [3dc2e5f](https://github.com/ASSERT-KTH/jdbl-experiments/commit/3dc2e5f877894023732459f69561971f61d0883e) has a `maven-proxy. xml` file, but this file has not appeared in the repository.

**Comment by tdurieux** [comment]
Could you read my message again?
